/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formATM;

import java.*;
import atm.*;
import formTell.MenuTeller;
import javax.swing.JOptionPane;

/**
 *
 * @author Anak Teknik Indo
 */
public class Transfer extends javax.swing.JFrame {

    private Bank bank;
    private Nasabah nasabah;

    /**
     * Creates new form Transfer
     */
    public Transfer(Nasabah nasabah, Bank bank) {
        initComponents();
        setLocationRelativeTo(null);
        this.nasabah = nasabah;
        this.bank = bank;
    }

    public Transfer() {
        initComponents();
        setLocationRelativeTo(null);
        bank = new Bank();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        inputNoRekNasabah = new javax.swing.JTextField();
        inputNominal = new javax.swing.JTextField();
        btnKembali = new javax.swing.JToggleButton();
        btnOk = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Transfer");

        inputNoRekNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoRekNasabahActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel2.setText("Nomor Rekening Tujuan");

        jLabel3.setText("Nominal Transfer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(inputNoRekNasabah)
                            .addComponent(inputNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNoRekNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(inputNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        int inputRek = Integer.parseInt(inputNoRekNasabah.getText());
        int nominal = Integer.parseInt(inputNominal.getText());

        if (inputRek == bank.getAllNasabah().get(0).getNoRek()) {
            nasabah.getTabungan().setAmbilSaldo(nominal);
            bank.getAllNasabah().get(0).getTabungan().setTambahSaldo(nominal);
            // nasabah.getTabungan().setTambahSaldo(nominal);
            //bank.getAllNasabah().get(0).getTabungan().setTambahSaldo(nominal);
            JOptionPane.showMessageDialog(null, "Pengiriman berhasil !!! \n" + "Nama Nasabah : " + bank.getAllNasabah().get(0).getNamaNasabah() + "\n No Rekening : " + bank.getAllNasabah().get(0).getNoRek() + "\nJumlah yang di transfer sebesar : " + nominal + "\nSisa saldo anda : " + nasabah.getTabungan().getSaldo());
        } else if (inputRek == bank.getAllNasabah().get(1).getNoRek()) {
            nasabah.getTabungan().setAmbilSaldo(nominal);
            bank.getAllNasabah().get(1).getTabungan().setTambahSaldo(nominal);
            // nasabah.getTabungan().setTambahSaldo(nominal);
            //bank.getAllNasabah().get(0).getTabungan().setTambahSaldo(nominal);
            JOptionPane.showMessageDialog(null, "Pengiriman berhasil !!! \n" + "Nama Nasabah : " + bank.getAllNasabah().get(1).getNamaNasabah() + "\n No Rekening : " + bank.getAllNasabah().get(1).getNoRek() + "\nJumlah yang di transfer sebesar : " + nominal + "\nSisa saldo anda : " + nasabah.getTabungan().getSaldo());
        } else if (inputRek == bank.getAllNasabah().get(2).getNoRek()) {
            nasabah.getTabungan().setAmbilSaldo(nominal);
            bank.getAllNasabah().get(2).getTabungan().setTambahSaldo(nominal);
            // nasabah.getTabungan().setTambahSaldo(nominal);
            //bank.getAllNasabah().get(0).getTabungan().setTambahSaldo(nominal);
            JOptionPane.showMessageDialog(null, "Pengiriman berhasil !!! \n" + "Nama Nasabah : " + bank.getAllNasabah().get(2).getNamaNasabah() + "\n No Rekening : " + bank.getAllNasabah().get(2).getNoRek() + "\nJumlah yang di transfer sebesar : " + nominal + "\nSisa saldo anda : " + nasabah.getTabungan().getSaldo());
        } else {
            JOptionPane.showMessageDialog(null, "No Rekening Tidak Ditemukan !!! ");

        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void inputNoRekNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoRekNasabahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoRekNasabahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Transfer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnKembali;
    private javax.swing.JToggleButton btnOk;
    private javax.swing.JTextField inputNoRekNasabah;
    private javax.swing.JTextField inputNominal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
